#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-distributed
Version  : 2022.4.1
Release  : 108
URL      : https://files.pythonhosted.org/packages/cd/04/cd190cd93b40bf34f2d91f9fad58b0cec3110b15b8c86dd48b8fe5ab5337/distributed-2022.4.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/cd/04/cd190cd93b40bf34f2d91f9fad58b0cec3110b15b8c86dd48b8fe5ab5337/distributed-2022.4.1.tar.gz
Summary  : Distributed scheduler for Dask
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-distributed-bin = %{version}-%{release}
Requires: pypi-distributed-license = %{version}-%{release}
Requires: pypi-distributed-python = %{version}-%{release}
Requires: pypi-distributed-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(click)
BuildRequires : pypi(cloudpickle)
BuildRequires : pypi(dask)
BuildRequires : pypi(jinja2)
BuildRequires : pypi(msgpack)
BuildRequires : pypi(packaging)
BuildRequires : pypi(psutil)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(sortedcontainers)
BuildRequires : pypi(tblib)
BuildRequires : pypi(toolz)
BuildRequires : pypi(tornado)
BuildRequires : pypi(urllib3)
BuildRequires : pypi(zict)

%description
Distributed
===========
|Test Status| |Longitudinal Report (full)| |Longitudinal Report (short)| |Coverage| |Doc Status| |Discourse| |Version Status| |NumFOCUS|

%package bin
Summary: bin components for the pypi-distributed package.
Group: Binaries
Requires: pypi-distributed-license = %{version}-%{release}

%description bin
bin components for the pypi-distributed package.


%package license
Summary: license components for the pypi-distributed package.
Group: Default

%description license
license components for the pypi-distributed package.


%package python
Summary: python components for the pypi-distributed package.
Group: Default
Requires: pypi-distributed-python3 = %{version}-%{release}

%description python
python components for the pypi-distributed package.


%package python3
Summary: python3 components for the pypi-distributed package.
Group: Default
Requires: python3-core
Provides: pypi(distributed)
Requires: pypi(click)
Requires: pypi(cloudpickle)
Requires: pypi(dask)
Requires: pypi(jinja2)
Requires: pypi(msgpack)
Requires: pypi(packaging)
Requires: pypi(psutil)
Requires: pypi(pyyaml)
Requires: pypi(sortedcontainers)
Requires: pypi(tblib)
Requires: pypi(toolz)
Requires: pypi(tornado)
Requires: pypi(urllib3)
Requires: pypi(zict)

%description python3
python3 components for the pypi-distributed package.


%prep
%setup -q -n distributed-2022.4.1
cd %{_builddir}/distributed-2022.4.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1650125141
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-distributed
cp %{_builddir}/distributed-2022.4.1/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-distributed/f016083f7994387778fdc4beb07d80240f8bbd54
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dask-scheduler
/usr/bin/dask-ssh
/usr/bin/dask-worker

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-distributed/f016083f7994387778fdc4beb07d80240f8bbd54

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
